language: python
python:
  - "3.4"
install: pip install -r requirements.txt
script:
  - python3 -m unittest
services:
  - redis-server

after_success:
  - sphinx-apidoc -f -o docs sputnik
  - cd docs && make dirhtml

deploy:
  provider: heroku
  api_key:
    secure: cqGXesHbnK3u42oQ/WgHjxzWQTRBlajqlbjl2DV33HHaQ+72xJKlw+3LDZoVFlunLrzDRqN4xyWmN7dTHyIkOhkDPZSaxfa84VSpBX19fHXJv8IJj13fyK6X1n/kipbEFQhosCV+Fuiz03f4bQ8xf9C6SSJ0T32F7uKABrFd/7Y=
  app:
    master: ganymede
  on:
    repo: Polytonic/Sputnik
