language: python
python:
  - "3.4"
install: pip install -r requirements.txt
before_script:
  - git submodule update --init --recursive
script:
  - coverage run --source=sputnik -m unittest
after_success:
  - flake8 sputnik tests
  - prospector sputnik tests
  - coveralls
services:
  - redis-server
